app/__init__.py
import os
from config import config
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_bootstrap import Bootstrap


db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'login'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
import requests
from . import main
from ..model import LoginForm, RegisterForm, User, Booklist, db
from flask import render_template, redirect, url_for, request, json, Response, current_app
from flask_login import login_required, logout_user, current_user, login_user
from werkzeug.security import check_password_hash, generate_password_hash

@main.route('/slack/', methods=['POST'])
def slack_verify():
    request_json = json.loads(request.data)
    return Response(request_json["challenge"], mimetype='application/x-www-form-urlencoded')

@main.route('/redirect/', methods=['POST'])
def redirect_main():
    token = request.form['token']
    team_id = request.form['team_id']
    query = request.form

    if token == current_app.config['VERIFICATION_TOKEN'] and team_id == current_app.config['TEAM_ID']:
        access_code = User.get_access_code(query)
        redirect_uri = request.url_root + '?access_code=' + access_code
        return redirect_uri
    else:
        return '사용자 인증에 실패 하셨습니다.'

@main.route('/', methods=['GET'])  # 자동 로그인, 인증되지 않을시 noauth로 redirect 한다.
def login():
    access_code = request.args.get('access_code')
    if access_code is None:
        return redirect(url_for('main.no_auth'))

    user = User.query.filter_by(temp_access_code=access_code).first()

    if user is None:
        return redirect(url_for('main.no_auth'))
    else:
        user = user.reset_access_code()
        login_user(user, remember=True)
        return redirect(url_for('main.index'))


@main.route('/noauth', methods=['GET'])  #인증되지 않은 사용자가 접근할때 나오는 페이지
def no_auth():
    return render_template('no_auth.html')


@main.route('/logout')  # 로그아웃
@login_required
def logout():
    logout_user()
    return redirect(url_for('login'))


# page route
@main.route('/home')  # 로그인 후 첫 페이지
@login_required  # 로그인한 사용자만 접근 가능
def index():
    return render_template('index.html', name=current_user.user_name)


@main.route('/mypage')  # 마이페이지
@login_required  ##로그인한 사용자만 들어갈 수 있게 설정
def mypage():
    return render_template('mypage.html')


@main.route('/add')  # 도서등록페이지
def add():
    return render_template('add.html')


@main.route('/addbook', methods=['POST'])  # 등록한 도서를 데이터 베이스에 추가
def addbook():
    name = request.form['name']
    author = request.form['author']
    kategorie = request.form['kategorie']
    status = request.form['status']
    date = request.form['date']

    booklist = Booklist(name=name, author=author, kategorie=kategorie, status=status, date=date)

    db.session.add(booklist)
    db.session.commit()

    return redirect(url_for('add'))


@main.route('/search', methods=['POST'])  # 검색 도서 목록
def search():
    book = request.form['book']
    lists = Booklist.query.filter(Booklist.name.like('%%%s%%' % book)).all()
    return render_template('table.html', lists=lists, name=current_user.user_name)


@main.route('/table')  # 도서 목록 페이지
def table():
    lists = Booklist.query.all()
    return render_template('table.html', lists=lists, name=current_user.user_name)


@main.route('/table2')  # 대출 가능 목록 페이지
def table2():
    lists = Booklist.query.filter_by(status='대출가능').all()
    return render_template('table.html', lists=lists, name=current_user.user_name)

app/templates/add.html
{% extends 'base.html' %}
{% block body %}
<!-- Main Content -->
<br>
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <form name="addForm" id="addForm" method="POST" action="{{ url_for('addbook') }}" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" name="name" id="name" required data-validation-required-message="Please enter a bookname.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Author</label>
              <input type="text" class="form-control" placeholder="Author" name="author" id="author" required data-validation-required-message="Please enter a author name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Kategorie</label>
              <input type="text" class="form-control" placeholder="Kategorie" name="kategorie" id="kategorie" required data-validation-required-message="Please enter a book kategorie.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Status</label>
              <input type="text" class="form-control" placeholder="Status" name="status" id="status" required data-validation-required-message="Book status">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Date</label>
              <input type="text" class="form-control" placeholder="Date" name="date" id="date" required data-validation-required-message="date">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" id="sendMessageButton">POST</button>
          </div>
        </form>
      </div>
    </div>
</div>
{% endblock body %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>블랙루비 도서대여시스템</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('static', filename='all.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='simple-line-icons.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='landing-page.min.css') }}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">HOME</a>
            <a class='btn' href="{{ url_for('main.mypage') }}"><strong>{{ name|capitalize }}</strong></a>
            <a class="btn" href="{{ url_for('main.logout') }}">Log out</a>
      </div>
    </nav>
    {% block body %}{% endblock body %}
  </body>

</html>

app/templates/index.html
{% extends 'base.html' %}
{% block body %}
    <!-- Masthead -->
    <header class="masthead text-white text-center" style="background-image: url('{{ url_for('static', filename='home-bg.jpg') }}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1>Blackruby</h1>
            <h2>Bookrental System</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form name="addForm" id="addForm" method="POST" action="{{ url_for('main.search') }}" novalidate>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="text" class="form-control form-control-lg" placeholder="도서명을 입력하세요..." name="book" id="book">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Search</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </header>

    <!-- Icons Grid -->
    <section class="features-icons bg-light text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <a href="{{ url_for('main.table') }}"><h3>전체 도서</h3></a>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <a href="{{ url_for('main.table2') }}"><h3>대출 가능</h3></a>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-0 mb-lg-3">
              <a href="{{ url_for('main.table') }}"><h3>도서 신청</h3></a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="footer bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
            <p class="text-muted small mb-4 mb-lg-0">&copy; 2018 blackruby 도서대여 사이트.</p>
          </div>
          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
          </div>
        </div>
      </div>
    </footer>
{% endblock body %}

app/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block body %}
<br>
    <div class="container">

      <form class="form-signin" method="POST" action="/">
        <h2 class="form-signin-heading">로그인을 해주세요</h2>
        {{ form.hidden_tag() }}
        {{ wtf.form_field(form.username) }}
        {{ wtf.form_field(form.password) }}
        {{ wtf.form_field(form.remember) }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
      </form>
      <br>
      <form action="{{ url_for('main.signup') }}">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
      </form>
    </div> 
{% endblock body %}

app/templates/mypage.html
{% extends 'base.html' %}

app/templates/no_auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Unauthorized User</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('static', filename='all.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='simple-line-icons.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='landing-page.min.css') }}" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    #snackbar {
        visibility: hidden;
        min-width: 250px;
        margin-left: -125px;
        background-color: #333;
        color: #fff;
        text-align: center;
        border-radius: 2px;
        padding: 16px;
        position: fixed;
        z-index: 1;
        left: 50%;
        bottom: 30px;
        font-size: 17px;
    }

    #snackbar.show {
        visibility: visible;
        -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;
        animation: fadein 0.5s, fadeout 0.5s 2.5s;
    }

    @-webkit-keyframes fadein {
        from {bottom: 0; opacity: 0;}
        to {bottom: 30px; opacity: 1;}
    }

    @keyframes fadein {
        from {bottom: 0; opacity: 0;}
        to {bottom: 30px; opacity: 1;}
    }

    @-webkit-keyframes fadeout {
        from {bottom: 30px; opacity: 1;}
        to {bottom: 0; opacity: 0;}
    }

    @keyframes fadeout {
        from {bottom: 30px; opacity: 1;}
        to {bottom: 0; opacity: 0;}
    }
    </style>
</head>
<body>
    <header class="text-black text-center">
        <img src="{{ url_for('static', filename='godsoonan.jpg') }}" width="650" style="margin:30px" />
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div id="god_words" class="col-xl-9 mx-auto">
                    <h3>내가 모르는 얼굴인데?</h3>
                    <h1>다시 Slack을 통해서 접근하도록 하여라</h1>
                </div>
                <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                        <div class="form-row">
                            <div class="col-12 col-md-9 mb-2 mb-md-0">
                                <input id="input" type="text" class="form-control form-control-lg" placeholder="하고싶은 말을 입력하세요" onkeypress="javascript:if(event.keyCode == 13){button_click();}">
                            </div>
                            <div class="col-12 col-md-3">
                                <button type="submit" onclick="button_click();" class="btn btn-block btn-lg btn-primary">대답하기</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>
    <div id="snackbar"></div>
</body>
<script>
    var myElem = document.getElementById('god_words')
    var child_list = myElem.children
    count = 0

    function input(){
        var input = document.getElementById("input").value;
        return input;
    }

    function print_message(temp){
        var x = document.getElementById("snackbar");
        x.innerHTML=temp
        x.className = "show";
        setTimeout(function(){ x.className = x.className.replace("show", ""); }, 2000);
    }

    function god_words(count){
        god_words_small = [
            "내말을 거역한 것인가?",
            "어허....이 놈 참 말 안듣는구나",
            "안되겠구나...",
            "크흠...소환이 실패하였구나....",
            "말이 안통하는 상대구나",
            "....."];
        god_words_bic = [
            "썩 꺼지거라!!!!",
            "Slack을 통해서 접근하라고 이몸이 말하였다.",
            "킹갓제너럴엠페러마이스터 경한님 소환!",
            "어쨋든 이제 그만 가거라. 이 몸은 바쁘다.",
            "더 이상 대답하지 않겠다.",
            "....."];

        if(count == 6){
            count = 5
         }

        child_list[0].innerText = god_words_small[count];
        child_list[1].innerText = god_words_bic[count];

        count += 1
        return count;
     }


    function button_click() {
        temp = input();
        document.getElementById("input").value = "";
        print_message(temp);
        count = god_words(count);
    }
</script>
</html>

app/templates/signup.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block body %}
<br>
<div class="container">

    <form class="form-signin" method="POST" action="/signup">
      <h2 class="form-signin-heading">가입 아직도 안했냐..? 불쾌하네요..</h2>
      {{ form.hidden_tag() }}
      {{ wtf.form_field(form.username) }}
      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
    </form>
  
  </div> 



{% endblock body %}

app/templates/table.html
{% extends 'base.html' %}

{% block body %}
    <br>
    <br>
    <header>
        <div class="container">
          <div class="row">
            <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
              <form name="addForm" id="addForm" method="POST" action="{{ url_for('main.search') }}" novalidate>
                <div class="form-row">
                  <div class="col-12 col-md-9 mb-2 mb-md-0">
                    <input type="text" class="form-control form-control-lg" placeholder="도서명을 입력하세요..." name="book" id="book">
                  </div>
                  <div class="col-12 col-md-3">
                    <button type="submit" class="btn btn-block btn-lg btn-primary">Search</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
    </header>
    <br>

{% for list in lists %}
<div class="container">
<hr>
    <h3>{{ list.name }}</h3>
    <br>
    <h5>{{ list.author }}</h5>
    <!-- 도서 정보 나머지 칸 추가 -->
</div>
<br>

{% endfor %}
{% endblock body %}